Sources/Music/Artist.swift

- Ensure there is whitespace after the prefix of "The", "A", "An"

Fix prefixes of "They" being mistaken for "The"

---

Sources/Site/Music/Album.swift
Sources/Site/Music/Music+Comparator.swift
Sources/Site/Utility/LibraryComparator.swift
Sources/site_tool/Program.swift

- LibraryComparator now also has a variant that just takes strings
- album comparison first sorts by date, then artist, then album title.

Add ability to sort albums better

---

Sources/Site/Utility/LibraryComparator.swift
Tests/SiteTests/LibraryComparatorTests.swift

- basically wrap `ZeroOrMore` in `Optionally`. I'd assumed zero or more meant it was optional...
- also capture one or more words and optional whitespace and use a whole match
- none of the tests expect failures now!

Fix the regex for library comparison

---

Tests/SiteTests/AlbumComparatorTests.swift

- Use test album titles that will sort properly. 
- -- "A Title" became "Title" which sorted after "B Title". :)

Fix album comparator tests

---

Sources/Site/Music/UI/ArtistList.swift
Sources/Site/Music/UI/LibraryComparableList.swift
Sources/Site/Music/UI/VenueList.swift
Sources/Site/Music/Vault.swift

- This way a pre-populated LibrarySectioner with a cache will be passed to every LibraryComparableList.

Add Vault.LibrarySectioner

---

Sources/Site/Music/Atlas+BatchGeocoding.swift
Sources/Site/Music/Atlas.swift
Sources/Site/Music/Vault.swift

- Implementation is tested and ready. It is not called at this time, since there is not yet a client.
- Handles ignoring most errors, except for when it has been throttled. If throttled, it will wait 60 seconds to try the next batch.
- The constants for the batch size and timeout were learned from the console log. Unfortunately the CLError does not have the underlying GEOError to dynamically learn the maxRequests and timeUntilReset values.
- Fixes #239

Add batch geocoding

---

Sources/Site/Music/UI/DeterminateTimerModifier.swift

- When the View this ViewModifier is attached to is gone the .task gets canceled, which throws.
- No longer getting a warm device. :)

Do not repeat in determinateTimer if there is an error

---

Sources/Site/Music/Lookup.swift
Sources/Site/Music/Music+Ranking.swift
Sources/Site/Music/UI/ArtistDetail.swift
Sources/Site/Music/UI/StatsGrouping.swift
Sources/Site/Resources/en.lproj/Localizable.strings

- Display it in the StatsGrouping for the ArtistDetail.
- The ordered ranking is also calculated; will cover that UI in a future diff.

Calculate Artist Show Count Rank

---

Sources/Site/Music/UI/ArtistList.swift
Sources/Site/Music/UI/LibraryComparableList.swift
Sources/Site/Music/UI/VenueList.swift

- This will allow it to be "empty" for certain UI situations (such as when the Section.header contains the information).

ViewBuilder LibraryComparable item content Views

---

Sources/Site/Music/UI/ArtistList.swift
Sources/Site/Music/UI/LibraryComparableList.swift
Sources/Site/Music/UI/VenueList.swift

- This is for the future when how these lists are shown changes.

Section headerView is calculated by a closure property

---

Sources/Site/Music/UI/ArchiveCategoryList.swift
Sources/Site/Music/UI/ArtistList.swift
Sources/Site/Music/UI/LibraryComparableList.swift
Sources/Site/Music/UI/VenueList.swift
Sources/Site/Resources/en.lproj/Localizable.strings

It's @Binding, and the @State is held in the parent of ArtistList and VenueList so they persist.
Fixes #242 Fixes #243 Fixes #244 Fixes #245

LibraryComparableList now has a switchable LibrarySectionAlgorithm

---

Sources/Site/Music/Music+Ranking.swift
Sources/Site/Music/PartialDate+Span.swift
Tests/SiteTests/PartialDateTests.swift

- Calendar.dateComponents(components:from:to) to the rescue!
- Fixes #313

Fix Year Span to match OS .relative formatting calculation

---

Sources/Site/Music/UI/LibraryComparableList.swift
Sources/Site/Music/UI/LibrarySectionAlgorithm.swift
Sources/Site/Resources/en.lproj/Localizable.strings

- Add the verb "sort" to the localized strings since iOS does not show the Menu name.

Wrap sorting algorithm Picker in a Menu

---

Sources/Site/Music/UI/ArtistList.swift
Sources/Site/Music/UI/LibraryComparableList.swift
Sources/Site/Music/UI/LibraryComparableSortModifier.swift
Sources/Site/Music/UI/VenueList.swift

- much like search moving this up and out allows clients to be able to attach it where it will work for them.

Add LibraryComparableSortModifier

---

Sources/Site/Music/UI/LocationMap.swift
Sources/Site/Utility/Locatable.swift
Sources/Site/Utility/Placemark+Geometry.swift

- It has an extension to calculate the MKCoordinateRegion.
- This is necessary since it is not possible (?!?) to create a hand rolled CLPlacemark for tests that has a center and a region.
- Make CLPlacemark conform to Locatable, and have LocationMap use the Locatable interface

Add Locatable protocol

---

Sources/Site/Music/UI/LocatableMap.swift
Sources/Site/Utility/Locatable.swift

Use it in LocatableMap. MapRects are simple to union for when LocatableMap has multiple locations.

Add Locatable.rect property

---

Sources/Site/Music/UI/ArtistList.swift
Sources/Site/Music/UI/RankingList.swift
Sources/Site/Utility/Ranking.swift

- It has a generic Ranking which will allow it to be anything (not just Int).
- It builds the section map dynamically, which will allow it to be sorted uniquely.
- LibrarySection.ranking is a workaround until more is refactored.
- ArtistList will use it for all sorting except ArtistSort.alphabetical

Add RankedList

---

Sources/Site/Music/UI/ArchiveCategory.swift
Sources/Site/Music/UI/ArchiveCategoryDetail.swift
Sources/Site/Music/UI/ArchiveCategorySplit.swift

- Making it non-optional allows it to be used by @SceneStorage.
- Add .none case to handle these; it should only exist when nothing is selected the first time the app is run.

Use SceneStorage for ArchiveCategory

---

Sources/Site/Music/ArchivePath.swift
Sources/Site/Music/UI/ArchiveCategorySplit.swift

This is a little tricky. When the List selection changes, it will reset the NavigationStack navigationPath. So when restoring state at launch in .task, if the selectedCategory and navigationPath both change, the navigationPath will be lost. The workaround is to hold onto the pending navigationPath, and set it after the selectedCategory has changed. Then forget about the pending navigationPath. Fixes #246

Save NavigationPath to SceneStorage.

---

Package.swift
Sources/site_associated_domains/Program.swift

- Unfortunately the format is not JSONEncodable since "appIDs" is an array of strings and "components" is an array of dictionaries.

Add a tool to generate associated domains json

---

Sources/Site/Music/UI/ArchiveCategorySplit.swift
Sources/Site/Music/UI/ArchiveNavigation.swift
Sources/Site/Music/UI/ArchiveStorageModifier.swift

This object will be used to coordinate that changing the `ArchivePath` may change the `ArchiveCategory`. This will have to be generalized beyond loading from `@SceneStorage` once other things can ask to show an `ArchivePath`.

Add ArchiveNavigation ObservableObject

---

Sources/Site/Music/UI/ArchiveNavigation.swift

- It just appends to the NavigationPath for simplicity (changing the category at the same time will lose the navigation path for as yet unknown reasons).

Add ArchiveNavigation.navigate(to) for ArchiveCategory and ArchivePath

---

Sources/Site/Music/Annum+NSUserActivity.swift
Sources/Site/Music/ArchivePath.swift
Sources/Site/Music/Artist+NSUserActivity.swift
Sources/Site/Music/Show+NSUserActivity.swift
Sources/Site/Music/UI/ArchiveCategorySplit.swift
Sources/Site/Music/UI/ArtistDetail.swift
Sources/Site/Music/UI/ShowDetail.swift
Sources/Site/Music/UI/VenueDetail.swift
Sources/Site/Music/UI/YearDetail.swift
Sources/Site/Music/Venue+NSUserActivity.swift

- Currently allows handoff of ArchivePath items.
- This successfully showed what was on macos on iphone. macos will show Handoff from the iphone in the Dock, but tapping on it does not trigger the continuation. Need to investigate if the macOS app needs to be built/installed differently.

Implement userActivity and onContinueUserActivity

---

Sources/Site/Music/UI/ArchiveStorageModifier.swift

Not sure why but it doesn't work if the enum (that is a String) is saved. Broken by #424

Store selectedArchiveCategory as String?

---

Sources/Site/Music/ArchivePath.swift
Sources/Site/Music/NSUserActivity+ArchivePath.swift
Sources/Site/Music/UI/PathRestorableUserActivityModifier.swift
Tests/SiteTests/PathRestorableUserActivityTests.swift

- This allows more detail to be logged when there is a failure, which for unknown reasons, still happens.
- ArchivePath no longer has a keyed Codable; it has the singleContainer again.
- Since typedPayload is no longer used for encoding, it no longer throws, and client code and tests can be updated to reflect that.

Use userInfo instead of typedPayload

---

Sources/Site/Music/Annum+NSUserActivity.swift
Sources/Site/Music/Artist+NSUserActivity.swift
Sources/Site/Music/NSUserActivity+ArchivePath.swift
Sources/Site/Music/Show+NSUserActivity.swift
Sources/Site/Music/UI/PathRestorableUserActivityModifier.swift
Sources/Site/Music/Vault+PreviewData.swift
Sources/Site/Music/Venue+NSUserActivity.swift
Tests/SiteTests/PathRestorableUserActivityTests.swift

- Vault is necessary to describe some upcoming NSUserActivity.

Pass Vault to NSUserActivity update

---

Sources/Site/Music/UI/VaultView.swift
Sources/Site/Music/VaultModel.swift

- Encapsulates the small logic for this code. 
- Allows it to be used by Commands, which need to be defined up for the Scene, which is not in this SPM.

Add VaultModel

---

Sources/Site/Music/VaultModel.swift

- Eliminates: "[SwiftUI] Publishing changes from background threads is not allowed; make sure to publish values from the main thread (via operators like receive(on:)) on model updates." message.

Annotate VaultModel with @MainActor

---

Sources/Site/Music/PathRestorableShareable.swift
Sources/Site/Music/UI/PathRestorableShareModifier.swift
Sources/Site/Music/UI/ShowDetail.swift

- Right now only Shows are shareable (since their IDs are most stable).
- Fixes #476

Add ShareLink for shows

---

Package.swift
Sources/stable_ids/Program.swift

- Basically just encode the ID into the raw data. That way it will not change. It requires careful editing when adding a new venue.
Steps:
- Read the JSON from the web to get the current venue IDs.
- Read the current raw venue data file used by web_generator.
- Look up the venue name and prepend the ID to the raw venue data.
- Update the web_generator code to require the manual venue ID, and to throw if any duplicate IDs are encountered.
See #233

Add a tool to create stable venue IDs

---

Sources/stable_ids/Program.swift

- Basically encode the show ID into the raw data used by web_generator.
- Read the JSON to get the latest IDs.
- Read the raw show data used by web_generator
- Look up the raw data's show ID using "date^artists^venue" as a "key"
- write out this new raw data
- need to update web_generator to read this new raw data format.
See #233

Convert tool to create stable show IDs

---

Sources/Site/Music/NSUserActivity+ArchivePath.swift
Tests/SiteTests/PathRestorableUserActivityTests.swift

- this allows other extensions to use the same names.

mark private parts appropriately

---

Sources/Site/Music/ArchivePath+FormatStyle.swift
Sources/Site/Music/ArchivePath+ParseableFormatStyle.swift
Sources/Site/Music/ArchivePath.swift
Sources/Site/Music/UI/ArchivePath+ArchiveCategory.swift
Sources/Site/Music/UI/MusicDestinationModifier.swift
Tests/SiteTests/ArchivePathTests.swift

This reverts commit 0f260de750d488e07943b6fef3d84f0b93642bb6.
- It's going via ArchiveCategory instead (See #497)

Revert "Add ArchivePath.today (#495)"

---

Sources/Site/Music/Lookup+Concert.swift
Sources/Site/Music/UI/ArtistBlurb.swift
Sources/Site/Music/UI/ArtistDetail.swift
Sources/Site/Music/UI/ConcertBlurb.swift
Sources/Site/Music/UI/MusicDestinationModifier.swift
Sources/Site/Music/UI/ShowDetail.swift
Sources/Site/Music/UI/TodayBlurb.swift
Sources/Site/Music/UI/TodayList.swift
Sources/Site/Music/UI/VenueBlurb.swift
Sources/Site/Music/UI/VenueDetail.swift
Sources/Site/Music/UI/YearDetail.swift
Sources/Site/Music/VaultModel.swift
Sources/site_tool/Program.swift
Sources/site_tool/Vault+Description.swift
Tests/SiteTests/PathRestorableUserActivityTests.swift

- it appears this will allow a Vault to more easily create Concerts while it is building instead of on-demand (as it is now).

Lookup now creates Concerts

---

Sources/Site/Music/ArchivePath+ParseableFormatStyle.swift
Tests/SiteTests/ArchivePathTests.swift

- Fixes when Safari detects stats pages and allows users to open them in the app. It will now correctly throw from ArchivePath, and then correctly create the ArchiveCategory.

Add ValidationError.invalidPrefix when parsing URLs into ArchivePath

---

Sources/Site/Music/UI/ArchiveCategoryDetail.swift
Sources/Site/Music/UI/ArchiveCategoryShareModifier.swift

- .shareCategory is now placed on a ZStack, so it can be used once.
- have this pass in the URL?

ArchiveCategoryShareModifier just takes a URL?

---

Sources/Site/Music/Lookup.swift
Sources/Site/Music/Music+ShowsOnly.swift
Sources/Site/Music/Vault+URL.swift
Sources/Site/Music/Vault.swift

- Remove Artist/Relations without Shows from Music, so everything else does not have to make assumptions.
- The problem is that ArtistMap and Relations contained Artists that did not have shows.

Add Music.showsOnly

---

Sources/Site/Music/Concert.swift
Tests/SiteTests/ConcertComparatorTests.swift

- Concert must conform to Equatable to pass these tests.
- Use concertMap lookup to remove dependency upon Vault being sorted while Music alone was not.
- Should have done this with #529

Test Concert compare instead of Show compare

---

Sources/Site/Music/Concert+FormatStyle.swift

- These were needed when this was Show.FormatStyle, but no longer!

Remove methods that can now be created by the compiler

---

Sources/Site/Music/UI/ArchiveCategoryDetail.swift
Sources/Site/Music/UI/ArtistList.swift
Sources/Site/Music/UI/VenueList.swift

- Now Vault isn't needed as an environment property.

LibrarySectioner is now a property

---

Sources/Site/Music/UI/LibraryComparableList.swift
Sources/Site/Music/UI/RankingList.swift

- not necessary in these previews.

Do not pass Vault to environment

---

Sources/Site/Music/UI/AddressView.swift
Sources/Site/Music/UI/ArchiveCategoryDetail.swift
Sources/Site/Music/UI/ArtistBlurb.swift
Sources/Site/Music/UI/ArtistDetail.swift
Sources/Site/Music/UI/ArtistList.swift
Sources/Site/Music/UI/ConcertBlurb.swift
Sources/Site/Music/UI/LibraryComparableList.swift
Sources/Site/Music/UI/RankingList.swift
Sources/Site/Music/UI/ShowDetail.swift
Sources/Site/Music/UI/ShowYearList.swift
Sources/Site/Music/UI/TodayBlurb.swift
Sources/Site/Music/UI/TodayList.swift
Sources/Site/Music/UI/VenueBlurb.swift
Sources/Site/Music/UI/VenueDetail.swift
Sources/Site/Music/UI/VenueList.swift
Sources/Site/Music/UI/YearDetail.swift
Tests/SiteTests/ConcertComparatorTests.swift
Tests/SiteTests/PathRestorableUserActivityTests.swift

- helps find remaining uses in library code.

Rename vault variable for tests and previews

---

Sources/Site/Music/Artist+Digest.swift
Sources/Site/Music/Show+Concert.swift
Sources/Site/Music/Vault.swift
Sources/Site/Music/Venue+Digest.swift

This way they are unaware of LibraryComparator, despite using it.

Create Digests with comparator closure

---

Sources/Site/Music/UI/ArchiveCategoryShareModifier.swift
Sources/Site/Music/UI/Bundle+AppIcon.swift
Sources/Site/Music/UI/PathRestorableShareModifier.swift

- It uses the subject and the AppIcon.
- Fixes #578

Add SharePreview to ShareLinks

---

Sources/Site/Music/UI/NotificationModifier.swift
Sources/Site/Music/VaultModel.swift

- The issue was the Notification is not sendable. We're not using any data from the Notification, so make it a Sequence of something else.
- Found via https://stackoverflow.com/questions/77070439/swift-silence-non-sendable-notification-cannot-cross-actor-boundary-warning

Fix Notification Non-Sendable warning

---

Sources/Site/Music/VaultModel.swift

- funcs now are @MainActor and the entire class is not.
Revert "Annotate VaultModel with @MainActor (#473)" 
This reverts commit ffcac209784687cd640e1f1c9b66df87fe34c0cd.

Implement updated MainActor approach

---

Sources/Site/Music/Atlas.swift
Sources/Site/Music/BatchGeocode.swift
Sources/Site/Music/Location+Geocode.swift
Sources/Site/Music/UI/MusicDestinationModifier.swift
Sources/Site/Music/Vault.swift
Sources/Site/Music/VaultModel.swift
Sources/Site/Music/Venue+Geocodable.swift
Sources/Site/Music/VenueDigest.swift

- Geocodable just means it has a geocode() func.
- AtlasGeocodable means it can be added in the Atlas cache (Codable, Equatable, Hashable).
- Location & Venue are therefore AtlasGeocodable.
- VenueDigest is not AtlasGeocodable, but something must be cached, so geocode its Venue.
- CNPostalAddress remains just Geocodable.

Add AtlasGeocodable

---

Sources/Site/Music/Atlas.swift
Sources/Site/Music/AtlasCache.swift
Sources/Site/Utility/Dictionary+JSONCache.swift
Sources/Site/Utility/FileManager+FileURL.swift
Sources/Site/Utility/NSCodingCodable.swift

- It reads from disk while initialized.
- It writes to disk with each value added.
- @NSCodingCodable wraps CLPlacemark so it is Codable to JSON
- Values expire, and are "staggered" in their expiration so they do not all happen on the same day after expiring.
- Fixes #238

Add AtlasCache

---

Sources/Site/Music/UI/ArchiveCategory+FormatStyle.swift
Sources/Site/Music/UI/ArchiveCategory.swift
Sources/Site/Music/UI/ArchiveCategoryDetail.swift
Sources/Site/Music/UI/ArchiveCategorySplit.swift
Sources/Site/Music/UI/NearbyBlurb.swift
Sources/Site/Music/UI/NearbyLabel.swift
Sources/Site/Music/UI/NearbyList.swift
Sources/Site/Music/Vault.swift
Sources/Site/Resources/en.lproj/Localizable.strings

- It will show the nearby shows if location access is granted.
- It will show a spinner if the venues are still all being geocoded.
- Fixes #237

Add Nearby Shows

---

Sources/Site/Music/Atlas.swift

Fixes:
```
/Users/bolsinga/Documents/code/git/site/Sources/Site/Music/BatchGeocode.swift:29:47: warning: passing argument of non-sendable type 'T' into actor-isolated context may introduce data races
let placemark = try await atlas.geocode(geocodable)
^
/Users/bolsinga/Documents/code/git/site/Sources/Site/Music/BatchGeocode.swift:11:21: note: consider making generic parameter 'T' conform to the 'Sendable' protocol
struct BatchGeocode<T: AtlasGeocodable>: AsyncSequence {
^
```

Declare AtlasGeocodable as Sendable

---

Sources/Site/Music/Concert.swift

Fixes:
```
/Users/bolsinga/Documents/code/git/site/Sources/Site/Music/Vault.swift:102:17: warning: capture of 'concerts' with non-sendable type '[Concert]' in 'async let' binding
concerts: concerts, baseURL: baseURL, lookup: lookup, comparator: comparator.compare(lhs:rhs:)
^
/Users/bolsinga/Documents/code/git/site/Sources/Site/Music/Concert.swift:10:15: note: consider making struct 'Concert' conform to the 'Sendable' protocol
public struct Concert: Equatable, Hashable, Identifiable {
^
, Sendable
```

Declare Concert Sendable

---

Sources/Site/Music/Atlas.swift
Sources/Site/Music/AtlasCache.swift

- internalize the staggering code. it was excessively complicated to be a closure.
- addresses a warning related to #653

Improve AtlasCache staggered expiration date

---

Sources/Site/Music/UI/NotificationModifier.swift

Task is not MainActor, so await MainActor action

---

Sources/Site/Utility/LocationManager.swift

- When LocationStream terminates, await the actor func terminate in a Task.
- Found by StrictConcurrency.
- Tested by calling continuation.finish() after 1 CLLocation received.

async LocationStream Termination

---

Sources/Site/Music/Atlas.swift

- Atlas now has an AtlasCache so this subscript indirection in Atlas is no longer necessary.

Remove indirection

---

Sources/Site/Utility/LocationManager.swift

- This allows the simulator location to work.
- It may also be the cause of the app not displaying information of a new location w/o a restart.

Unknown Location Errors do not end LocationStream with error

---

Sources/Site/Music/UI/MusicDestinationModifier.swift

- This was hard to "fix" because it compiled w/o the `import CoreLocation`. Adding that then emitted the fix-it when building.
Fixes:
```
/Users/bolsinga/Documents/code/git/site/Sources/Site/Music/UI/MusicDestinationModifier.swift:25:37: warning: non-sendable type 'CLPlacemark' returned by implicitly asynchronous call to actor-isolated function cannot cross actor boundary
try await vault.atlas.geocode($0.venue)
^
CoreLocation.CLPlacemark:2:12: note: class 'CLPlacemark' does not conform to the 'Sendable' protocol
open class CLPlacemark : NSObject, NSCopying, NSSecureCoding {
^
/Users/bolsinga/Documents/code/git/site/Sources/Site/Music/UI/MusicDestinationModifier.swift:8:2: remark: add '@preconcurrency' to suppress 'Sendable'-related warnings …
```

Use @preconcurrency CoreLocation

---

Sources/Site/Music/UI/ArchiveCategorySplit.swift
Sources/Site/Music/VaultModel.swift

- This basically is a small change to have nearbyConcerts be a function instead of a property.
- It sets up the code to allow this threshold to be changed by the user in a future diff.

Use SceneStorage for nearbyDistanceThreshold

---

Sources/Site/Music/UI/ArchiveCategoryDetail.swift
Sources/Site/Music/UI/ArchiveCategorySplit.swift
Sources/Site/Music/VaultModel.swift

Basically, @SceneStorage is not global, but the VaultModel is global.
Revert "nearbyConcerts is now a computed property of VaultModel (#698)"
This reverts commit 6efec077806931254ddfdb76e245bc4f6fea22ed.

Fix when different Scenes have different nearbyDistanceThresholds.

---

Sources/Site/Music/NearbyModel.swift
Sources/Site/Music/UI/ArchiveCategoryDetail.swift
Sources/Site/Music/UI/ArchiveCategorySplit.swift
Sources/Site/Music/UI/LocationFilterModifier.swift

- This is necessary because onChange: does not always update geocoding to 1.0, despite it being 1.0
- Instead of trying to pass the properties from VaultModel to NearbyModel and assuming that works (is this a bug???), have NearbyModel have a VaultModel to just get the property values directly.
- Looking for a way to have two Observable models where they can be independent instead of dependent. Not now, however.
- This was a bug in #726 that was not observed right away. :(

NearbyModel now has a VaultModel

---

Sources/Site/Music/NSUserActivity+ArchiveCategory.swift
Sources/Site/Music/UI/ArchiveCategorySplit.swift

- pass it into category methods.
- Unable to keep it as an instance property when building on 5.9 on GitHub. Things worked fine locally with swift 5.10

decode category activity logger is a local variable

---

Sources/Site/Music/UI/RefreshCommand.swift

- Moves the concurrency warning up to the app, so this is just kicking the can...

RefreshCommand is not agnostic of the model

---

Sources/Site/Music/UI/ArtistList.swift
Sources/Site/Music/UI/ArtistSort.swift
Sources/Site/Music/UI/SortModifier.swift
Sources/Site/Music/UI/VenueList.swift
Sources/Site/Music/UI/VenueSort.swift

- The intent is soon that ArtistSort and VenueSort become one in the same, but they need to separate the type from the localized name to do that.

SortModifier now takes a closure for the algorithm name

---

Sources/Site/Music/ArtistDigest.swift
Sources/Site/Music/Rankable.swift
Sources/Site/Music/VenueDigest.swift

- Add extension helpers to Array of Rankable.
- ArtistDigest and VenueDigest are now Rankable, and do not need specialized extensions on Array anymore.

Add Rankable protocol

---

Sources/Site/Music/UI/ArchiveCategoryDetail.swift
Sources/Site/Music/UI/ArtistList.swift
Sources/Site/Music/UI/VenueList.swift

- #794 broke when there were "no items" in that it was confused if there were none by location filter or if by search not finding anything

Move searching into ArtistList / VenueList

---

Sources/Site/Music/UI/ArtistList.swift
Sources/Site/Music/UI/RankableSortList.swift
Sources/Site/Music/UI/RankingList.swift
Sources/Site/Music/UI/VenueList.swift
Sources/Site/Utility/String+EmphasizedMatching.swift

- RankingList now defers rendering LibraryComparable.name to a closure
- ArtistList and VenueList will render their names emphasizing the searchString in the UI.

Search string is emphasized (bold) in UI

---

Package.swift

This reverts commit 1ef924934f610c420773c76118b9b8ed4457a8bc.
This will work now that github actions are using Xcode 15.4

Revert "backup to .4 releases since github does not have .5 (#820)"

---

Sources/Site/Music/Atlas.swift
Sources/Site/Music/AtlasCache.swift
Sources/Site/Music/Lookup.swift
Sources/Site/Music/Music+URL.swift
Sources/Site/Music/NSUserActivity+ArchiveCategory.swift
Sources/Site/Music/NSUserActivity+ArchivePath.swift
Sources/Site/Music/SiteModel.swift
Sources/Site/Music/UI/ArchiveCategorySplit.swift
Sources/Site/Music/UI/ArchiveNavigation.swift
Sources/Site/Music/UI/ArchiveStorageModifier.swift
Sources/Site/Music/UI/NotificationModifier.swift
Sources/Site/Music/UI/SiteView.swift
Sources/Site/Music/Vault+URL.swift
Sources/Site/Music/VaultModel.swift
Sources/Site/Utility/Data+JSON.swift
Sources/Site/Utility/LocationManager.swift

Fixes #824
Revert "Convert Link Logger to a local variable (#762)"
This reverts commit 1edd225d494cca3ff5b7a18cb43c0671b9d52cb2.
Revert "Convert Archive Logger to an instance property (#763)"
This reverts commit fd6323a9bb869feecd54394f3ce76e92671eeb8c.
Revert "Convert Storage Logger to an instance property (#764)"
This reverts commit cd3e5ebc71192bf9fb3e110ea8a1af86e63aac5e.
Revert "Convert VaultLoad Logger to an instance property (#765)"
This reverts commit 160d1d3bb7346af10b1dcbfd7855513d0541decb.
Revert "Convert AtlasCache Logger to an instance property (#767)"
This reverts commit d053bf693ddf7a123d263246422b4057762858d5.
Revert "Convert Atlas Logger to an instance property (#766)"
This reverts commit 231461c6ba96da7912bdc76856931e42946c2e0e.
Revert "Convert vault Logger to a local …

Just annotate logging concurrency issues for Swift 6.0

---

Sources/Site/Music/UI/ArchiveCategoryDetail.swift
Sources/Site/Music/UI/ArtistDetail.swift
Sources/Site/Music/UI/MusicDestinationModifier.swift
Sources/Site/Music/UI/PathRestorableLink.swift
Sources/Site/Music/UI/ShowDetail.swift
Sources/Site/Music/UI/VenueDetail.swift
Sources/Site/Music/UI/YearDetail.swift

- This will prevent navigating to PathRestorables already in the navigation path.

Add PathRestorableLink and use it

---

Sources/Site/Music/UI/ArchiveNavigation.swift
Tests/SiteTests/ArchiveNavigationTests.swift

- Any navigationPath will then be pending, not set immediately.

ArchiveNavigation.restoreNavigation allows selectedCategory to be set to nil

---

Sources/Site/Music/UI/ArchiveNavigation.swift
Tests/SiteTests/ArchiveNavigationTests.swift

- logicalliy with no category selected, there cannot be a navigationPath.

ArchiveNavigation.restoreNavigation with nil category clears the path

---

Sources/Site/Music/VaultModel.swift
Sources/Site/Utility/LocationManager.swift

Use CLLocationUpdate

---

Sources/Site/Music/UI/VenueDetail.swift

follow up to #738. Xcode16 RC warned about declaring CLPlacemark was Identifiable, when the library may change that in the future.

VenueDetail no longer needs to know about CLPlacemark

---

Sources/Site/Music/UI/Bundle+AppIcon.swift

iOS18 AppIcon name no longer works

---

Sources/Site/Music/UI/ArchiveNavigation.swift
Sources/Site/Music/UI/ArchiveStateView.swift
Tests/SiteTests/ArchiveNavigationTests.swift

Add accessor methods. The goal is to hide the serialization so it can change.

ArchiveNavigation.State is now a private property

---

Sources/Site/Music/UI/ArchiveCategoryDetail.swift
Sources/Site/Music/UI/ArchiveCategorySplit.swift

This is setting up for saving the state for each category. Basically there will not be a single [ArchivePath] soon.

Add closure to get [ArchivePath] from a ArchiveCategory

---

Sources/Site/Music/UI/ArchiveNavigation.swift
Tests/SiteTests/ArchiveNavigationTests.swift

This way the each category has its own path, making this a little better. It will also work better for tabs, which will have multiple NavigationStack paths.

Store each category's path

---

Tests/SiteTests/ArchiveNavigationTests.swift

- This tests what happens when ArchiveNavigation moves from one category with a path to another category, and then back.
- Basicallly what happens is the path is cleared. This is likely not preferred behavior going forward.

Add category/path test

---

Sources/Site/Music/UI/ArchiveCategoryShareActivityModifier.swift
Sources/Site/Music/UI/ArchiveCategorySplit.swift
Sources/Site/Music/UI/CategoryDetailModifier.swift

It is now a modifier to the NavigationSplitView sidebar List. As selection changes, each ArchiveCategory will toggle isActive appropriately.

ArchiveCategory userActivity now toggles isActive

---

Sources/Site/Music/LocationFilter.swift
Sources/Site/Music/NearbyModel.swift
Sources/Site/Music/UI/ArchiveStateView.swift
Sources/Site/Music/UI/LocationFilterModifier.swift
Sources/Site/Music/UI/NearbyDistanceThresholdModifier.swift

- This way NearbyModel's State is persisted via @SceneStorage. It removes persisting code from the various modifiers for this state.
- Insprired by the work done for ArchiveNavigation in #845

Add NearbyModel.State

---

Sources/Site/Music/AnnumDigest+NSUserActivity.swift
Sources/Site/Music/ArtistDigest+NSUserActivity.swift
Sources/Site/Music/Concert+NSUserActivity.swift
Sources/Site/Music/NSUserActivity+Search.swift
Sources/Site/Music/VenueDigest+NSUserActivity.swift

Hide CoreSpotlight stuff that doesn't support tvOS in an extension to reduce OS checks at compile time.

abstract away searchable content description

---

Sources/Site/Music/NearbyModel.swift
Sources/Site/Music/UI/ArchiveNavigation.swift

This allows the json string to be used for the CustomStringConvertible. However can't make State RawRepresentable for a String, since State is also Codable, and if it is RawRepresentable, there will be an infinite loop.
This is basically getting rid of a "saving" archive log when that isn't what was happening. Just save that for the RawRepresentable stubs, and allow with logs to access the JSON directly.

Separate ArchiveNavigation/NearbyModel.State json String from description and RawRepresentable

---

Sources/Site/Music/UI/ArchiveCategory+Summary.swift
Sources/Site/Music/UI/ArchiveCategoryDetail.swift
Sources/Site/Music/UI/ArchiveCategoryRoot.swift
Sources/Site/Music/UI/ArchiveCategoryStack.swift
Sources/Site/Music/UI/StatsSummary.swift

- This bubbles up to ArchiveCategoryStack and will be able to used by other views (such as tabs).

StatsSummary exposes displayArchiveCategoryCounts too

---

Sources/Site/Music/Location+Geocode.swift

They do not need to be. In the newer geocoding code in OS 26, more informaton from Venue may be passed, so Location will have some, but not all of the data that would be useful for Geocoding.

Locations are no longer AtlasGeocodable

---

Sources/Site/Music/Atlas.swift
Sources/Site/Music/AtlasCache.swift
Sources/Site/Music/BatchGeocode.swift
Sources/Site/Music/Geocode.swift
Sources/Site/Music/Location+Geocode.swift
Sources/Site/Music/Placemark.swift
Sources/Site/Music/UI/VenueDetail.swift
Sources/Site/Music/VaultModel.swift
Sources/Site/Music/Venue+Geocodable.swift
Sources/Site/Utility/NSCodingCodable.swift
Sources/Site/Utility/Placemark+Geometry.swift

This is because in OS 26 there is better functionality for geocoding in MapKit.

Atlas no longer depends upon CLPlacemark

---

Sources/Site/Music/UI/RankableSortList.swift
Sources/Site/Music/UI/RankingList.swift

When building with Xcode 26 Beta it fixes the following warning:
```
22 |       ForEach(rankingMap.keys.sorted(by: rankSorted ?? (<)), id: \.self) { ranking in
|                                                         |- error: sending '$base$' risks causing data races [#SendingRisksDataRace]
|                                                         `- note: task-isolated '$base$' is captured by a main actor-isolated closure. main actor-isolated uses in closure may race against later nonisolated uses
```
See https://github.com/bolsinga/site/actions/runs/15714862525/job/44281967115#step:6:249

RankingList.rankSorted is non-Optional

---

Sources/Site/Music/UI/ArchiveNavigation.swift
Sources/Site/Music/UI/ArchivePath+ArchiveCategory.swift
Tests/SiteTests/ArchiveNavigationTests.swift
Tests/SiteTests/ArchivePathTests.swift

- This exposed an issue where changing both the category and path would *clear* the path.
- In an 1-1 SwiftUI lab WWDC25, this was the known workaround suggested by the team.
- Test URLs in a simulator with:
```
xcrun simctl openurl booted https://www.bolsinga.com/bands/ar1416.html
```
- Without this workaround, changing the category will update the UI such that the path is cleared after the first property changes.
- When both properties change, do not animate the first category property change  to eliminate a double animation.
- When both properties change, make the path change on the next turn of the RunLoop with an animation.
- **NOTE:** This use of DispatchQueue.main is the reason why this class is @MainActor. If this is removed in the future, remove the annotation from the class too.

When externally navigating to a path, set the category

---

Sources/Site/Music/UI/ArchivePath+Destination.swift
Sources/Site/Music/UI/VenueDetail.swift

- With Xcode 16.4 / non OS 26 / Swift 6.1,  MKMapItem is not Sendable, so it must be marked @preconcurrency.
- Shoe-horn in a conditional check for Swift 6.2 once we can go there. I think this should be conditional on the targetted SDK version, but I'm not sure how to do that at this level in the code.

Raise Geocoded MKMapItem up, since it is the OS 26 geocoding result.

---

Sources/Site/Music/UI/ArchiveCategoryStack.swift

It was removed in #1022, but is useful for `TabView` work.

Keep ArchiveCategoryStack for TabView implementation.

---

Sources/Site/Music/UI/ArchiveCategoryRoot.swift
Sources/Site/Music/UI/ArchiveSettingsPlacement.swift
Sources/Site/Music/UI/ArchiveTabView.swift
Sources/Site/Music/UI/LocationFilterToolbarContent.swift
Sources/Site/Resources/Localizable.xcstrings

- iPhone nearby toggle is now a Menu. A quick tap will toggle, and a press for the menu will bring up an option to show the SettingsView
- just iPhone will not show settings in the TabView

Location Distance Editing via Toolbar on iPhone

---

Sources/Site/Music/UI/ArchiveCategoryStack.swift
Sources/Site/Music/UI/ArchiveTabView.swift
Sources/Site/Music/UI/DaysShowsSummary.swift
Sources/Site/Music/UI/ShowsMode.swift

- Make a private ArchiveTab enum. This tracks the Tab selection. 
- -- It knows its ArchiveCategory. Pass this along to the rest of the UI code. 
- -- It will change the ArchiveCategory @Binding so that the ArchiveStateView will share the proper category.
- Track the ShowsMode of the DaysShowsSummary in the ArchiveTabView. 
- -- When it changes, change the @Binding ArchiveCategory, but not the selected ArchiveTab.
- Also fixes the ArchiveNavigation save/restore in AppStorage.

ShowsMode breaks userActivity / restoration (iPhone only)

---

Sources/Site/Music/UI/ArchiveCategory+FormatStyle.swift
Sources/Site/Music/UI/ArchiveCategory+LocationFilterable.swift
Sources/Site/Music/UI/ArchiveCategory+URL.swift
Sources/Site/Music/UI/ArchiveCategory.swift
Sources/Site/Music/UI/ArchiveCategoryStack.swift
Sources/Site/Music/UI/ArchiveCategoryToolbarContent.swift
Sources/Site/Music/UI/ArchiveNavigation.swift
Sources/Site/Music/UI/ArchiveStateView.swift
Sources/Site/Music/UI/ArchiveTabView.swift
Sources/Site/Resources/Localizable.xcstrings
Tests/SiteTests/ArchiveCategoryTests.swift
Tests/SiteTests/ArchiveNavigationTests.swift

- Doing this this way since it touches so many files!
- This is necessary even with Tab's .search role. This is because your code needs a value that also means "search" for the Tab. If it is added to ArchiveTab, it must be added to ArchiveCategory too.
- This is so that ArchiveNavigation knows that it is showing Search so that when a search result is tapped on, the navigation to the ArchivePath will do the right thing and change from the Search tab to the right ArchiveCategory.

Add ArchiveCategory.search

---

Sources/Site/Music/UI/ArchiveStateView.swift
Sources/Site/Music/UI/ArchiveTabView.swift

- this is because the active category may be different from the selected tab.

rename to activeCategory for clarity

---

SiteApp.xcodeproj/project.pbxproj
Sources/Intents/ArtistEntityQuery.swift
Sources/Intents/VenueEntityQuery.swift

- Use 5 recent shows.
- Remove duplicate venues or artists.
- The order is now reversed, so the show nearest today or recent will be first, not last.
- Artists are ordered headliner followed by support for each show used (today or recent).

Use recent shows if today had no shows

---

Sources/Site/Music/UI/ArchiveStateView.swift

- Opening a universal URL on macOS Sequoia will still not open the proper location on macOS. However the same url works for `NSUserActivity`.
- Building macOS on Tahoe in a Virtual Machine fails when the universal links entitlement is added, so this will have to be revisited once development is primarily on Tahoe.

Use handlesExternalEvents to get handoff to open in the same window on macos

---

Sources/Site/Music/Atlas.swift
Sources/Site/Music/AtlasCache.swift

It used to be the entire `Venue`. Now it is just the `Venue.ID`. Launching again will re-geocode everything, which is fine.

Atlas cache file is Venue.ID -> CLPlacemark data
