- Sources/json/Album.swift
- Sources/json/Artist.swift
- Sources/json/Diary.swift
- Sources/json/Entry.swift
- Sources/json/Location.swift
- Sources/json/Music.swift
- Sources/json/PartialDate.swift
- Sources/json/Relation.swift
- Sources/json/Show.swift
- Sources/json/Song.swift
- Sources/json/Venue.swift
- prepration for the json code being in a library.
> Make the structs and properties public

- Sources/json/Album.swift
- Sources/json/Artist.swift
- Sources/json/Diary.swift
- Sources/json/Entry.swift
- Sources/json/Location.swift
- Sources/json/Music.swift
- Sources/json/PartialDate.swift
- Sources/json/Relation.swift
- Sources/json/Show.swift
- Sources/json/Song.swift
- Sources/json/Venue.swift
- this allows mock data to be simply created for SwiftUI Previews.
> use let properties, add public memberwise initializers

- Sources/json/Music+Description.swift
- Sources/json/Music+Lookup.swift
- Sources/json/Music.swift
- Sources/json/PartialDate+Date.swift
- Sources/site_tool/Program.swift
- Once JSON is loaded, add lookup dictionarys to go from id to object 
-- ignore the properties for Codable that are the lookup maps by implementing the Codable implementations manually.
- Add description code for Show and PartialDate so that this lookup code can be tested, along with some debugging help.
- Add a PartialDate to Date conversion for those that can be converted.
> Add Music Lookup and descriptions

- Sources/Music/Album.swift
- Sources/Music/Music+Description.swift
- Sources/Music/Music+Lookup.swift
- Sources/Music/PartialDate+Date.swift
- Sources/Music/PartialDate.swift
- Sources/Music/UI/ShowView.swift
- Sources/site_tool/Program.swift
- just use all nil properties to indicate it is unknown 
-- albums' dates came in as unknown, but knew the year.
- Add test data to the UI to exercise this code.
- Add sort albums by date code to program to see even more.
> Remove PartialDate unknown json property

- Sources/Music/Artist.swift
- Sources/Music/Music+Description.swift
- Sources/Music/Music+Lookup.swift
- Sources/site_tool/Program.swift
- Add `RegexBuilder` for comparing artist names. 
-- it ignores leading whitespace and punctuation (handling "(Smog)" and "...And You Will Know Us By The Trail Of Dead" properly).
-- This `Regex` can be the basis of sorting album and song names soon too.
> Allow Artist to be Comparable

- Sources/Music/Artist.swift
- Ran https://github.com/bolsinga/web_generator/blob/46407d0b27a6e489b9ce652be61234388323cab1/src/com/bolsinga/music/Compare.java#L17 through https://swiftregex.com/ and understood even more.
> Better prefix/postfix matching

- Sources/Music/Venue.swift
- basically bring https://github.com/bolsinga/web_generator/pull/97 here.
> Add Venue.sortname

- Sources/Music/Album.swift
- Sources/Music/Music+Description.swift
- Required in order to build the web site from json created from this code.
> Add Album.compilation optional property

- Package.swift
- Sources/site_tool/LoadingState+Diary.swift
- Sources/site_tool/LoadingState+Music.swift
- Music and Diary are just data and logic for now.
> Have the program depend upon LoadingState

- Sources/site_tool/Program.swift
- Sources/site_tool/URL+JSON.swift
- pass --json /path/to/directory 
-- a directory will be created there and diary.json and music.json will be written there (after reading from the input root URL).
> Allow this to export json.

- Sources/Site/Music/Music+Comparator.swift
- Sources/Site/Music/Show.swift
- Sources/site_tool/Program.swift
- if dates are the same (usually unknown in my dataset), sort by venue name if available.
> Improve Show comparison

- Sources/Site/Utility/LibraryComparator.swift
- Tests/SiteTests/LibraryComparatorTests.swift
- also fix/support ignoring case
> Separate regex prefix trimming

- Sources/Site/Music/Music+Comparator.swift
- Tests/SiteTests/ShowComparatorTests.swift
Fix an edge case while we're at it
> Add Show Comparator Tests

- Sources/Site/Music/Location.swift
- Sort hierarchially (State, City, Street if available).
> Improve/Simplify Location Comparable

- Sources/Site/Music/LoadingState+MapItem.swift
- tried this out in the cmd-line program, and it was throttled. but it works!
> Geocode Location -> MKMapItem

- Sources/Site/Music/Music+Description.swift
- Sources/Site/Music/Music+Lookup.swift
- Sources/Site/Music/UI/ArtistView.swift
- Sources/Site/Music/UI/ShowBlurbView.swift
- Sources/site_tool/Program.swift
- Add lookup for Artist -> [Show]
> Add Shows to ArtistView

- Sources/Site/Music/UI/ArtistView.swift
> Do not show albums

- Sources/Site/Music/Music+Lookup.swift
- Sources/Site/Music/PartialDate+Date.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
- Sources/Site/Resources/en.lproj/Localizable.stringsdict
- Add show count
- Add years of shows (will eventually navigate to a ShowList).
> Add Venue Shows

- .github/workflows/main.yml
- .github/workflows/release.yml
- just keep macos only `swift build`
> Disable xcodebuild for now

- Sources/Site/Music/String+Markdown.swift
- Sources/Site/Music/UI/ShowDetail.swift
- allows external links to work
> Render Show.comment as markdown

- Sources/Site/Music/UI/VenueList.swift
- Sources/Site/Utility/LibraryComparator.swift
- Tests/SiteTests/LibraryComparatorTests.swift
- Do not assume it is just one letter removed.
> Fix sectioned venues by calculating librarySection

- Sources/Site/Music/UI/NavigateTab.swift
> Each TabItem is a NavigationStack

- Sources/Site/Music/UI/LibraryComparableList.swift
- Just make a [String: [Item]] map once per render
> Calculate section map more quickly

- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Music/UI/LibrarySectionIndexModifier.swift
Borrowed from: https://stackoverflow.com/questions/58809357/swiftui-list-with-section-index-on-right-hand-side
> Add LibrarySectionIndex

- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Music/UI/LibrarySectionIndexModifier.swift
- Sources/Site/Utility/FormatStyle+LibrarySection.swift
- Sources/Site/Utility/LibrarySection.swift
- Tests/SiteTests/LibrarySectionTests.swift
- debt owed to: https://ampersandsoftworks.com/posts/formatstyle-parseableformatstyle-and-your-custom-types/
> Add LibrarySection.FormatStyle

- Sources/Site/Music/UI/ArchiveCategory.swift
- Sources/Site/Music/UI/NavigateTab.swift
- It has localized strings and a label.
> Add ArchiveCategory enum

- Sources/Site/Music/UI/ArchiveCategoryList.swift
- use async let to concurrently build up the arrays
> load archive items as @State from .task

- Sources/Site/Music/UI/ArchiveCategoryList.swift
- eliminates a log msg about localization not found too.
> Use FormatStyle for the archive item counts

- Sources/Site/Utility/LibraryComparable.swift
- Sources/Site/Utility/LibraryComparator.swift
- Sources/Site/Utility/LibrarySection.swift
- Add convenience property to get the librarySortToken
> Move LibraryComparable into its own file

- Sources/Site/Utility/LibraryComparator.swift
- Sources/Site/Utility/LibrarySection.swift
- Sources/Site/Utility/String+LibrarySorting.swift
- Tests/SiteTests/LibraryComparatorTests.swift
- convert them from funcs to properties too.
> Move Library Sorting Helpers to extensions on String

- Sources/Site/Music/FormatStyle+PartialDate.swift
- Sources/site_tool/Music+Description.swift
- need to make more parts of PartialDate.FormatStyle public.
> Move Music+Description into the tool, since it is not used by the module

- Sources/Site/Music/Album.swift
- Sources/Site/Music/Relation.swift
- Sources/Site/Music/Song.swift
- Sources/Site/Music/Vault.swift
- requires some things to conform to Identifiable.
> Use generics for Vault lookups

- Sources/Site/Music/Lookup.swift
- Sources/Site/Music/UI/ArchiveCategoryList.swift
- Sources/Site/Music/UI/ArtistDetail.swift
- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Music/UI/NavigateTab.swift
- Sources/Site/Music/UI/ShowBlurb.swift
- Sources/Site/Music/UI/ShowDetail.swift
- Sources/Site/Music/UI/ShowYearList.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Music/UI/VenueList.swift
- Sources/Site/Music/Vault+Comparator.swift
- Sources/Site/Music/Vault.swift
- Sources/site_tool/Program.swift
- Sources/site_tool/Vault+Description.swift
- Vault now has a Lookup (which everything now must reference).
- This will allow Vault to be created by a caller that may popupate Lookup asynchronously.
> Separate Lookup from Vault

- Sources/Site/Music/Lookup.swift
- Sources/site_tool/Program.swift
- Sources/site_tool/Vault+Description.swift
- albumMap is only needed by site_tool, so move it into there.
> Remove relation and song lookups

- Sources/Site/Music/LibraryComparator+Shows.swift
- Sources/Site/Music/UI/ArchiveCategoryList.swift
- Sources/Site/Music/UI/ArtistDetail.swift
- Sources/Site/Music/UI/NavigateTab.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Music/Vault.swift
- Sources/Site/Utility/LibraryComparator.swift
- Sources/site_tool/LibraryComparator+Albums.swift
- Sources/site_tool/Program.swift
- Tests/SiteTests/LibraryComparatorTests.swift
- Tests/SiteTests/ShowComparatorTests.swift
- This will allow it to have some associated data caches.
> Make LibraryComparator into a struct

- .github/workflows/main.yml
- .github/workflows/release.yml
> try swift test

- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Utility/LibrarySection.swift
- Sources/Site/Utility/LibrarySectioner.swift
- Tests/SiteTests/LibrarySectionTests.swift
- This will allow it to have some state.
> Add LibrarySectioner struct

- Sources/Site/Music/UI/ArchiveCategoryList.swift
- Sources/Site/Music/UI/MonthChart.swift
- Sources/Site/Music/UI/Stats.swift
- Sources/Site/Music/UI/WeekdayChart.swift
- This will allow them to be used in more places.
> Pass [Show] into Stats views

- Sources/Site/Music/UI/TodayBlurb.swift
- It surfaces the artist names along with the venue and date.
> Add TodayBlurb and use it in TodayList

- Sources/Site/Music/UI/VenueDetail.swift
- Handles unknown years properly.
> Use PartialDate formatter in VenueDetail

- Sources/Site/Music/UI/VenueBlurb.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
- Sources/Site/Resources/en.lproj/Localizable.stringsdict
- List the shows with artists and dates
- Summary # of shows, # of years, and # of artists in a concise manner.
> Refine VenueDetail

- Sources/Site/Music/UI/ArtistDetail.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
- Sources/Site/Resources/en.lproj/Localizable.stringsdict
- List the # of shows, # of years, # of venues
> Refine ArtistDetail

- Sources/Site/Music/UI/ArchiveCategoryList.swift
- Sources/Site/Music/UI/ArchiveStats.swift
- Sources/Site/Music/UI/Stats.swift
- This is what has the ScrollView so the embedded ones do not; it makes the layout better.
> Add ArchiveStats

- Sources/Site/Music/UI/ArchiveCategoryList.swift
- Sources/Site/Music/Vault.swift
Sort them while building the Vault.
> Store sorted Artists, Venues, Shows in Music

- Sources/Site/Music/UI/ArchiveCategoryList.swift
- Sources/Site/Utility/Date+Midnight.swift
- Tests/SiteTests/DateMidnightTests.swift
- These parts work; something still seems to be up elsewhere.
> Refactor some of the Timer / midnight stuff for testing.

- Sources/Site/Music/UI/ArchiveCategoryList.swift
- @State the todayShows [Show]
- The timer starts with a manual Date.now pushed in, so all the changing of the @State happens from the .onReceive.
- Wrap the changing of the @State in such that it will be called in a little bit. Not sure why SwiftUI needs this. There are many examples on the web, where I don't understnad the why.
> Fix Today's Shows Count updating at midnight

- Sources/Site/Music/UI/ArchiveCategoryList.swift
- Sources/Site/Music/UI/DeterminateTimerModifier.swift
- This encapsulates the details in a ViewModifier.
- upcoming work to have this handle/understand when the app is in the background!
> Add DeterminateTimerModifier

- Sources/Site/Music/UI/ArchiveCategoryList.swift
- Sources/Site/Music/UI/DeterminateTimerModifier.swift
- This will allow more flexibility in the future
> Add a trigger parameter to DeterminateTimerModifier

- Sources/Site/Music/UI/DeterminateTimerModifier.swift
The action should be called in .onAppear, and then in the .onReceive for the Timer thereafter.
> Fix making the initial call.

- Sources/Site/Music/UI/DeterminateTimerModifier.swift
- Sources/Site/Utility/Date+Midnight.swift
- Tests/SiteTests/DateMidnightTests.swift
- This will allow a Timer to be rebuilt on scenePhase changes in a subsquent diff.
> Use TriggerDate as constant

- Sources/Site/Music/UI/DeterminateTimerModifier.swift
- This startDate is the @State that will change when ScenePhase changes.
> Store the startDate as @State

- Sources/Site/Utility/Date+Midnight.swift
- Tests/SiteTests/DateMidnightTests.swift
This partially reverts commit b3ca822038a21abb4dd0da700b154cef4b76f0da.
> Bring back timeIntervalUntilMidnight

- Sources/Site/Music/UI/DeterminateTimerModifier.swift
- Cool structured concurrency for the win!
- it looks like this will behave as expected even while in the background.
> Use Task.sleep(until:clock:)

- Sources/Site/Music/Atlas+BatchGeocoding.swift
- Sources/Site/Music/Atlas.swift
- This will allow us to observe subscripting. Not sure if this could be done with a property wrapper.
> Add subscript support to Atlas.

- Sources/Site/Music/Atlas.swift
- Sources/Site/Music/UI/ArchiveCategoryList.swift
- Sources/Site/Music/Vault.swift
- Not wired up yet, but tested it out.
- This will populate a @State so that the locations start showing up on a VenueMap
> Add AsyncStream to Atlas to get cached Location geocodes

- Sources/Site/Music/LibrarySectioner+Music.swift
- Sources/Site/Music/UI/LibrarySection+Section.swift
- Sources/Site/Music/Vault.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
- Sources/Site/Utility/FormatStyle+LibrarySection.swift
- Sources/Site/Utility/FormatStyle+Ranking.swift
- Sources/Site/Utility/LibrarySection.swift
- Sources/Site/Utility/Ranking.swift
- When added to a LibraryComparableList, the data is sectioned with this new code!
> Add LibrarySection.ranking and create LibrarySectioner based upon that data

- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Music/UI/VenueList.swift
- its messy and will make subsequent diffs cleaner
> Switch around parameters

- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/VenueList.swift
- this got in while I was testing!
> do not use rankSectioner yet

- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Music/UI/VenueList.swift
- custom versions for ArtistList and VenueList.
> Add LibraryComparableListHelper

- Sources/Site/Music/LibrarySectioner+Music.swift
- Sources/Site/Music/Vault.swift
- This will allow the Artist and Venues to be ordered by how long shows have been seen there or by them.
> Add showSpanSectioner

- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Music/UI/VenueList.swift
- Need to think like a SwiftUI programmer. The helper was some sort of a object that you'd pass in and change which isn't how this system works.
> LibraryComparableList just uses properties again.

- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/Vault+LibrarySectioner.swift
- Sources/Site/Music/UI/VenueList.swift
- This basically will provide a different way of sectioning the list when the algorithm changes
> extend Vault to provide a LibrarySectioner based upon the LibrarySectionAlgorithm

- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/LibrarySectionAlgorithm+LibrarySection.swift
- Sources/Site/Music/UI/VenueList.swift
- This way each items contentView (basically the right hand side of the list item) is customizable based upon the algorithm.
> extend LibrarySectionAlgorithm to have a itemContentView func

- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Music/UI/LibrarySectionAlgorithm+LibrarySection.swift
- Sources/Site/Music/UI/VenueList.swift
- This way the Section headerView is customizable based upon the algorithm.
> extend LibrarySectionAlgorithm to have a headerView func

- Sources/Site/Music/UI/LibrarySectionAlgorithm+LibrarySection.swift
- Sources/Site/Music/UI/Ranking+ViewRepresentations.swift
This allows more customization.
> Add Ranking.viewRepresentations

- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Music/UI/VenueList.swift
- Now LibrarySectionAlgorithm is fully encapsulated. This means it may now change!
> Encapsulate itemContentView by just getting the value with a closure

- Sources/Site/Music/UI/ShowDetail.swift
- Show the relative Date if possible.
- Fixes #300
> Make ShowDetail date into a Section

- Sources/Site/Music/UI/AddressView.swift
- Sources/Site/Music/UI/ArchiveCategoryList.swift
- Sources/Site/Music/UI/ArchiveCategoryStack.swift
- Sources/Site/Music/UI/ArtistBlurb.swift
- Sources/Site/Music/UI/ArtistDetail.swift
- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Music/UI/LocationMap.swift
- Sources/Site/Music/UI/MonthChart.swift
- Sources/Site/Music/UI/ShowBlurb.swift
- Sources/Site/Music/UI/ShowDetail.swift
- Sources/Site/Music/UI/ShowList.swift
- Sources/Site/Music/UI/ShowYearList.swift
- Sources/Site/Music/UI/StateChart.swift
- Sources/Site/Music/UI/TodayBlurb.swift
- Sources/Site/Music/UI/TodayList.swift
- Sources/Site/Music/UI/VenueBlurb.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Music/UI/VenueList.swift
- Sources/Site/Music/UI/WeekdayChart.swift
- Sources/Site/Music/Vault+PreviewData.swift
- SPM does not filter out Previews at this time, so make a global accessor.
- Also remove some not very useful Previews.
> Add Vault.previewData

- Sources/Site/Music/UI/ShowDetail.swift
> Do not show relative dates if the date is unknown

- Sources/Site/Music/Decade.swift
- Sources/Site/Music/FormatStyle+Decade.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
- Tests/SiteTests/DecadeTests.swift
- Add accessors properties to Date and PartialDate
- Add FormatStyles
- Add tests
> Add Decade enum

- Sources/Site/Music/Lookup.swift
- Sources/Site/Music/Music+Ranking.swift
I thought the arrays would be used, but they are not.
> Only store the ranking maps

- Sources/Site/Music/UI/TodayList.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
> Show information when there are no shows today.

- Sources/Site/Music/UI/YearDetail.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
> Add stats to the YearDetail

- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Music/UI/LibraryComparableSearchModifier.swift
- Sources/Site/Music/UI/VenueList.swift
- Starts the way to refactor the search to have suggestions and be scoped.
> Refactor LibraryComparableSearch out into a ViewModifier

- Sources/Site/Music/UI/LocatableMap.swift
- Sources/Site/Music/UI/LocationMap.swift
- Sources/Site/Utility/Locatable.swift
- This will be the basis of testing as well as a map with many Locatable items.
> Add LocatableMap and have LocationMap use it.

- Sources/Site/Music/UI/LocatableMap.swift
- Sources/Site/Music/UI/LocationMap.swift
- Sources/Site/Utility/Locatable.swift
- Add a paddedRect accessor that expands by 10% so that the annotations are not right next to the edge of the screen.
> LocatableMap now has an array of Locatables.

- Sources/Site/Music/UI/LocatableMap.swift
- Sources/Site/Music/UI/LocationMap.swift
- It will allow external additions or removals of Locatables.
- It will update the mapRect State when the locations change.
> LocatableMap has Binding of Locatables and State of mapRect

- Sources/Site/Music/LibrarySectioner+Music.swift
- Sources/Site/Music/Lookup.swift
- Sources/Site/Music/Music+Ranking.swift
- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/LibrarySectionAlgorithm+LibrarySection.swift
- Sources/Site/Music/UI/LibrarySectionAlgorithm.swift
- Sources/Site/Music/UI/Ranking+ViewRepresentations.swift
- Sources/Site/Music/UI/StatsGrouping.swift
- Sources/Site/Music/UI/Vault+LibrarySectioner.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Music/Vault.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
- display it in the stats, allow venues to be sorted this way.
> Rank Venues by # of Artists

- Sources/Site/Music/BatchGeocode.swift
This way if there is any waiting due to an error, it will reset the batch counter to try for a full batch again.
> Add BatchGeocode.idleAndReset() and use it reset batch counting

- Sources/Site/Music/UI/LibrarySectionAlgorithm.swift
- Sources/Site/Music/UI/SortModifier.swift
This will help split things up down the line.
> Make SortModifier generic

- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Music/UI/VenueList.swift
It now no longer depends upon LibrarySectionAlgorithm!
> Externalize LibraryComparableList item ContentView

- Sources/Site/Music/UI/ArchiveCategoryList.swift
- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/ArtistSort.swift
- Sources/Site/Music/UI/LibrarySectionAlgorithm+LibrarySection.swift
- Sources/Site/Music/UI/LibrarySectionAlgorithm.swift
- Sources/Site/Music/UI/Vault+LibrarySectioner.swift
- Sources/Site/Music/UI/VenueList.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
- also remove LibrarySectionAlgorithm.artistVenueRank
> Separate artist sorting from the rest

- Sources/Site/Music/ParseableFormatStyle+Annum.swift
- Tests/SiteTests/AnnumTests.swift
- This will allow them to be written / read from JSON strings.
> Add Annum ParseableFormatStyle

- Sources/Site/Music/ArchivePath.swift
- Sources/Site/Music/FormatStyle+ArchivePath.swift
- Sources/Site/Music/ParseableFormatStyle+ArchivePath.swift
- Tests/SiteTests/ArchivePathTests.swift
- this will help out with json encoding
> Add ArchivePath FormatStyle and ParsableFormatStyle

- Sources/Site/Music/UI/ArchiveCategory.swift
- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArchiveCategorySplit.swift
This reverts commit 5cebcfb17a2f79fa76d2b22715a752d64d1f6fcf.
- It is not possible to have non-Optional selection on iOS
> Revert "Use SceneStorage for ArchiveCategory (#401)"

- Sources/Site/Music/ArchivePath+ParseableFormatStyle.swift
- Tests/SiteTests/ArchivePathTests.swift
- https://github.com/bolsinga/web_generator/pull/135 is what makes this simpler
> Handle new URL format

- Sources/Site/Music/ArchivePath.swift
- This allows it to be used with NSUserActivity.typedPayload
> ArchivePath Codable now uses CodingKey

- Sources/Site/Music/UI/ArchiveCategory.swift
- Sources/Site/Music/UI/ArchiveNavigation.swift
- Sources/Site/Music/UI/ArchiveStorageModifier.swift
- Simplifies storage for sure!
> ArchiveCategory enum is a String

- Sources/Site/Music/Music+URL.swift
- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Sources/Site/Music/UI/ArchiveNavigation.swift
- Sources/Site/Music/UI/ArchiveStorageModifier.swift
- Sources/Site/Music/UI/VaultView.swift
- Sources/Site/Music/Vault+URL.swift
- Sources/Site/Utility/Data+JSON.swift
> Add Logger statements for debugging

- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Add a log so maybe this can be debugged in the logs...
- See #232
> universal links

- Sources/Site/Music/Annum+NSUserActivity.swift
- Sources/Site/Music/ArchivePath.swift
- Sources/Site/Music/Artist+NSUserActivity.swift
- Sources/Site/Music/Show+NSUserActivity.swift
- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Sources/Site/Music/UI/ArtistDetail.swift
- Sources/Site/Music/UI/PathRestorableUserActivityModifier.swift
- Sources/Site/Music/UI/ShowDetail.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Music/UI/YearDetail.swift
- Sources/Site/Music/Venue+NSUserActivity.swift
It encapsulates the logic with generics. this will allow all to be customized in one place, as well as specifically for each.
> Add pathRestorableUserActivityModifier

- Sources/Site/Music/Annum+NSUserActivity.swift
- Sources/Site/Music/Artist+NSUserActivity.swift
- Sources/Site/Music/Venue+NSUserActivity.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
> Add Spotlight search for Artist, Venue, Annum

- Sources/Site/Music/Annum+NSUserActivity.swift
- Sources/Site/Music/Artist+NSUserActivity.swift
- Sources/Site/Music/Show+NSUserActivity.swift
- Sources/Site/Music/UI/PathRestorableUserActivityModifier.swift
- Sources/Site/Music/Venue+NSUserActivity.swift
- also do this in one place, since it's available! NEAT-O
> log errors when creating userActivity

- Sources/Site/Music/NSUserActivity+ArchivePath.swift
- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Sources/Site/Music/UI/PathRestorableUserActivityModifier.swift
- Tests/SiteTests/PathRestorableUserActivityTests.swift
> Extend NSUserActivity for creating/decoding

- Sources/Site/Music/UI/WeekdayChart.swift
> Take firstDayOfWeek user setting into account in WeekdayChart

- Sources/Site/Music/Location.swift
- Sources/Site/Music/PartialDate+Date.swift
- Sources/Site/Utility/CompareOptional.swift
Does not involve converting to Foundation.Date on the fly so often!
> Simpler PartialDate comparison

- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/ArtistSort.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
> Add ArtistSort.firstSeen

- Sources/Site/Music/UI/VenueList.swift
- Sources/Site/Music/UI/VenueSort.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
> Add VenueSort.firstSeen

- Sources/Site/Music/NSUserActivity+ArchivePath.swift
- Tests/SiteTests/PathRestorableUserActivityTests.swift
-- Since they are still confusing.
> Have user activity expire

- Sources/Site/Music/Show+FormatStyle.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
- Sources/site_tool/Program.swift
- Sources/site_tool/Vault+Description.swift
- Had to pass in Lookup; see comments for the details of how to ignore it for Codable, Equatable, Hashable. :/
> Add Show.FormatStyle

- Sources/site_associated_domains/Program.swift
This typo fix may help out #232
> applinks not appLinks

- Sources/Site/Music/PathRestorableShareable.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Now that Venue IDs are stable they can be shared. See https://github.com/bolsinga/web_generator/pull/137
> Share a Venue

- Package.swift
- Sources/Site/Music/Vault+URL.swift
- Sources/Site/Music/Vault.swift
- Sources/artist_ids/Program.swift
> Add tool to create Artist -> IDs file

- Sources/Site/Music/PathRestorableShareable.swift
- Sources/Site/Music/UI/ArtistDetail.swift
- Now that IDs are stable, they can be shared!
> Share an Artist

- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Sources/Site/Music/UI/ArchiveNavigation.swift
- Tests/SiteTests/ArchiveNavigationTests.swift
ArchiveNavigation.navigate(to:) needs clarification (if ArchivePath.today is added!)
> Clarify what is being navigated to

- Sources/Site/Music/ArchivePath+FormatStyle.swift
- Sources/Site/Music/ArchivePath+ParseableFormatStyle.swift
- Sources/Site/Music/ArchivePath.swift
- Sources/Site/Music/UI/ArchivePath+ArchiveCategory.swift
- Sources/Site/Music/UI/MusicDestinationModifier.swift
- Tests/SiteTests/ArchivePathTests.swift
- Soon this will be able to be shared / hand-off / etc
> Add ArchivePath.today

- Sources/Site/Music/UI/ArchiveCategory+FormatStyle.swift
- Sources/Site/Music/UI/ArchiveCategory+ParseableFormatStyle.swift
- Sources/Site/Music/UI/ArchiveCategory.swift
- Tests/SiteTests/ArchiveCategoryTests.swift
- This will be used for handoff / sharing / MORE for ArchiveCategories (esp. .today).
> Add Formatting / Parsing : ArchiveCategory <-> URL

- Sources/Site/Music/UI/VaultView.swift
- Sources/Site/Music/VaultModel.swift
- This way refreshable returns and the UI will stop showing a refresh
- Add more logging to track this stuff.
- Caused by #488
> monitorDayChanges in a separate Task

- Sources/Site/Music/NSUserActivity+ArchiveCategory.swift
- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArchiveCategoryShareModifier.swift
- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Sources/Site/Music/UI/ArchiveCategoryUserActivityModifier.swift
- Sources/Site/Music/Vault.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
- Handoff, sharing, universal links work.
> Create ArchiveCategory <-> NSUserActivity

- Sources/Site/Music/NSUserActivity+ArchiveCategory.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
- And other parts for prediction
> Add Siri suggested innvocation phrase

- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Sources/Site/Music/UI/ArchiveCategoryUserActivityModifier.swift
If there is any navigationPath, then ArchiveCategory is not active, and the ArchivePath is.
> Only advertise ArchiveCategory when it is active

- Sources/Site/Music/UI/ArchiveCategory.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
> Update title for ArchiveCategory.today

- Sources/Site/Music/LibraryComparator+Shows.swift
- Sources/Site/Music/Lookup.swift
- Sources/Site/Music/Show+FormatStyle.swift
- Sources/Site/Music/UI/ShowBlurb.swift
- Sources/Site/Music/UI/ShowDetail.swift
- Sources/Site/Music/UI/StatsGrouping.swift
- Sources/Site/Music/UI/TodayBlurb.swift
- Sources/Site/Music/UI/VenueBlurb.swift
- All clients would catch the exception and create an empty array, so just get what we can get!
> Lookup.artistsForShow() no longer throws

- Sources/Site/Music/PathRestorable.swift
- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Sources/Site/Music/UI/Concert.swift
- Sources/Site/Music/UI/TodayBlurb.swift
- Sources/Site/Music/UI/TodayList.swift
- Sources/Site/Music/UI/Vault+Concert.swift
- Sources/Site/Music/VaultModel.swift
- It's a fully formed POD that has Show Venue, and [Artist] so they do not have to be "looked up" along the way.
- Subsequent PRs will use this in more places.
> Add Concert and use it in TodayList / TodayBlurb

- Sources/Site/Music/Annum+NSUserActivity.swift
- Sources/Site/Music/Artist+NSUserActivity.swift
- Sources/Site/Music/Concert+NSUserActivity.swift
- Sources/Site/Music/NSUserActivity+ArchivePath.swift
- Sources/Site/Music/UI/PathRestorableShareModifier.swift
- Sources/Site/Music/UI/PathRestorableShareable.swift
- Sources/Site/Music/UI/PathRestorableUserActivityModifier.swift
- Sources/Site/Music/Venue+NSUserActivity.swift
- make some of these into read-only properties.
> Do not pass Vault to funcs that no longer need it.

- Sources/Site/Music/LibraryComparator+Concert.swift
- Sources/Site/Music/VaultModel.swift
- Sources/site_tool/Program.swift
- just like LibraryComparator.showCompare, but without Lookups!
> LibraryComparator : Concert

- Sources/Site/Music/UI/ArtistBlurb.swift
- Sources/Site/Music/UI/ConcertBlurb.swift
- Sources/Site/Music/UI/ShowDetail.swift
- Sources/Site/Music/UI/TodayBlurb.swift
- Sources/Site/Music/UI/TodayList.swift
- Sources/Site/Music/UI/VenueBlurb.swift
- Sources/Site/Music/Vault.swift
> Compute Concerts up-front in Vault

- Sources/Site/Music/Vault+NextID.swift
> remove import

- Sources/Site/Music/Lookup.swift
- Sources/Site/Music/Music+Ranking.swift
- Sources/Site/Music/UI/MusicDestinationModifier.swift
- Sources/Site/Music/UI/ShowYearList.swift
- Sources/Site/Music/UI/YearDetail.swift
- Sources/Site/Music/Vault.swift
- DecadesMap now hold Show.ID instead of Show
> YearDetail now takes [Concert]

- Sources/Site/Music/UI/LocationMap.swift
- Sources/Site/Music/UI/VenueDetail.swift
- No longer depends upon Vault.
> LocationMap now takes geocoding closure

- Sources/Site/Music/NSUserActivity+ArchivePath.swift
- Sources/Site/Music/UI/ArtistDetail.swift
- Sources/Site/Music/UI/MusicDestinationModifier.swift
- Sources/Site/Music/UI/PathRestorableUserActivityModifier.swift
- Sources/Site/Music/UI/ShowDetail.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Music/UI/YearDetail.swift
- Tests/SiteTests/PathRestorableUserActivityTests.swift
- This means ArtistDetail and YearDetail need URL? too.
> Pass ArchivePath URL instead of Vault for NSUserActivity

- Sources/Site/Music/Lookup.swift
- Sources/Site/Utility/LibraryComparator.swift
- This helps making refactoring this code simpler to understand
> Make more properties private

- Sources/Site/Music/UI/MusicDestinationModifier.swift
- Sources/Site/Music/UI/ShowDetail.swift
- Sources/Site/Music/Vault+AnnumDigest.swift
- Sources/Site/Music/Vault+ArtistDigest.swift
- Sources/Site/Music/Vault+VenueDigest.swift
- Sources/Site/Music/Vault.swift
- Tests/SiteTests/PathRestorableUserActivityTests.swift
- neglected to do this in #575
> Use ArchivePath.url() in all the places

- Sources/Site/Music/Vault.swift
- This allows the create() to build this asynchronously.
> Pass [Concert] into Vault initializer

- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArtistDetail.swift
- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Music/UI/MusicDestinationModifier.swift
- Sources/Site/Music/UI/RankingList.swift
- Sources/Site/Music/UI/ShowDetail.swift
- Sources/Site/Music/UI/ShowYearList.swift
- Sources/Site/Music/UI/TodayList.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Music/UI/VenueList.swift
- Sources/Site/Music/UI/YearDetail.swift
This makes things more explicit going forward.
> Pass Vault to MusicDestinationModifier

- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ShowYearList.swift
- Sources/Site/Music/Vault.swift
- Therefore Vault no longer needs to store Lookup
> Vault now stores DecadesMap

- Sources/Site/Music/AnnumDigest.swift
- Sources/Site/Music/ArtistDigest.swift
- Sources/Site/Music/UI/ArtistDetail.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Music/UI/YearDetail.swift
- Sources/Site/Music/Vault+AnnumDigest.swift
- Sources/Site/Music/Vault.swift
- Sources/Site/Music/VenueDigest.swift
AnnumDigest, ArtistDigest, VenueDigest all know how to sort their Concerts (just in case).
> Ensure things are sorted

- Sources/Site/Music/ArtistDigest.swift
- Sources/Site/Music/Vault.swift
- Sources/Site/Music/VenueDigest.swift
- Sources/site_tool/Program.swift
- make some bits public for the Program.
- Allows Vault.comparator to be internal.
> Update Program to use more of Vault

- Sources/Site/Music/UI/MusicDestinationModifier.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Music/Vault.swift
- Sources/Site/Music/VenueDigest.swift
> Move geocode closure to VenueDetail

- Sources/Site/Music/UI/VaultView.swift
- Sources/Site/Music/VaultModel.swift
- the guard in the .task prevents previews from actually loading
> Add VaultView previews

- Sources/Site/Music/UI/VaultView.swift
- Sources/Site/Music/VaultModel.swift
- eliminates a force unwrap in the app.
> Pass URL as string to VaultModel

- Sources/Site/Music/UI/VaultView.swift
- Sources/Site/Music/VaultModel.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
- Reset VaultModel.error to nil when load() is called.
> Add retry button if there is a VaultModel.error

- Sources/Site/Music/Atlas.swift
- Sources/Site/Music/BatchGeocode.swift
- Sources/Site/Music/Vault.swift
- Sources/Site/Music/VenueDigest.swift
- This way the Atlas has Identifiable items in its lookup, which are also Geocodable.
- Now only the VenueDigest needs to be an AtlasItem.
> Add AtlasItem : Geocodable, Identifiable

- Sources/Site/Music/VaultModel.swift
-- hard codes a location for now... :)
> Add func to calculate nearby Concerts

- Sources/Site/Music/VaultModel.swift
- Sources/Site/Utility/LocationManager.swift
- Wraps CLLocationManager, and provides async stream of CLLocation. Authorization issues are throws to simplify client code greatly.
- Inspired by https://github.com/markiv/SwiftAsyncShims
> Add LocationManager

- Sources/site_tool/Program.swift
> Remove spurious awaits

- Sources/Site/Music/Atlas.swift
- Sources/Site/Music/BatchGeocode.swift
- Sources/Site/Music/VaultModel.swift
- Sources/Site/Music/VenueDigest.swift
- Sources/Site/Utility/Locatable.swift
- Remove some import CoreLocation where not necessary
> Add CoreLocation @preconcurrency

- Sources/Site/Music/Album.swift
- Sources/Site/Music/Artist.swift
- Sources/Site/Music/Location.swift
- Sources/Site/Music/Music.swift
- Sources/Site/Music/PartialDate.swift
- Sources/Site/Music/Relation.swift
- Sources/Site/Music/Show.swift
- Sources/Site/Music/Song.swift
- Sources/Site/Music/Venue.swift
> Music structs are Sendable since immutable

- Sources/Site/Music/Annum.swift
- Sources/Site/Music/Decade.swift
- Sources/Site/Music/Lookup.swift
- Sources/Site/Utility/Rank.swift
- Sources/Site/Utility/Ranking.swift
- includes things it depends upon.
- found by StrictConcurrency
> Declare Lookup Sendable

- Sources/Site/Utility/LibraryComparator.swift
> Declare LibraryComparator as Sendable

- Sources/Site/Music/ArtistDigest.swift
- Sources/Site/Music/FirstSet.swift
- Sources/Site/Music/Vault.swift
- Sources/Site/Music/VenueDigest.swift
> Declare Vault as Sendable

- Sources/Site/Utility/LocationManager.swift
- surfaced by StrictConcurrency
> LocationManager is now an actor

- Sources/Site/Music/UI/NotificationModifier.swift
- Just moves the issue up to WeekdayChart, but its a start.
> Declare NotificationManager.action as Sendable

- Sources/Site/Music/UI/NotificationModifier.swift
> NotifcationModifer calls its action on MainActor

- Sources/Site/Music/UI/VenueDetail.swift
> Declare VenueDetail.locationElement @MainActor

- Sources/Site/Music/Atlas.swift
- Sources/Site/Music/AtlasCache.swift
- Ensures the dictionary is accessed via the actor.
- Trying to make geocoding a little more better for StrictConcurrency
> Make AtlasCache into an actor

- Sources/Site/Music/VaultModel.swift
- Sources/Site/Utility/LocationManager.swift
- Add more logging since I experienced odd location behavior.
> More Location logging

- Package.swift
> Enable StrictConcurrency

- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Sources/Site/Music/UI/LocationFilterModifier.swift
- Sources/Site/Music/UI/ShowYearList.swift
- Sources/Site/Music/UI/VenueFilter.swift
- Sources/Site/Music/UI/VenueList.swift
- Sources/Site/Resources/en.lproj/Localizable.strings
- Use it in VenueList and ShowYearList to filter nearby shows
- This allows nearby items to be sorted just as one would expect.
> Add LocationFilter and Toggle

- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Raises warnings once VaultModel is declared Observable.
> Declare ArchiveCategorySplit.sidebar MainActor

- Package.swift
See discussion in https://github.com/apple/swift-package-manager/issues/6993
> Declare Localizable.xcstrings as a resource

- Sources/Site/Music/UI/LocationFilterModifier.swift
- Sources/Site/Resources/Localizable.xcstrings
> Use ContentUnavailableView for location restricted or denied

- Sources/Site/Music/UI/VaultView.swift
- Sources/Site/Resources/Localizable.xcstrings
> Use ContentUnavailableView when unable to load Vault data

- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Music/UI/RankingList.swift
> Use ContentUnavailableView.search for searchables

- Sources/Site/Music/UI/TodayList.swift
- Sources/Site/Resources/Localizable.xcstrings
> Use ContentUnavailableView when there are no shows on this date

- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Sources/Site/Music/VaultModel.swift
- need to set nearbyDistanceThreshold when it changes
> nearbyConcerts is now a computed property of VaultModel

- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArchiveCategorySplit.swift
ArchiveCategoryDetail does not change this, so it does not need to be @Binding
> todayConcerts is now a let constant

- Sources/Site/Music/UI/VaultView.swift
- Sources/Site/Music/VaultLoader.swift
- Sources/Site/Music/VaultModel+PreviewData.swift
- Sources/Site/Music/VaultModel.swift
> fix preview data

- Sources/Site/Music/SiteModel.swift
- Sources/Site/Music/UI/SiteView.swift
- Sources/Site/Music/VaultModel+PreviewData.swift
- Sources/Site/Music/VaultModel.swift
- Current plan is that there is one SiteModel, and a new VaultModel for each reload of the SiteModel...
> Rename VaultView to SiteView, VaultLoader to SiteModel

- Sources/Site/Music/VaultModel.swift
...so dependent computed property updates when observed
follow-up to #721
> observe geocoded placemarks 

- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
Found after logging added with #722
> Only calculate what is nearby once per render

- Sources/Site/Music/NearbyModel.swift
- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Sources/Site/Music/UI/LocationFilterModifier.swift
- Sources/Site/Music/UI/NearbyDistanceThresholdModifier.swift
- Sources/Site/Music/VaultModel.swift
- @SceneStorage for nearbyDistanceThreshold is now in NearbyDistanceThresholdModifier
- @SceneStorage for locationFilter is now in LocationFilterModifier
- VaultModel.locationAuthorization is pushed into NearbyModel when it changes.
- VaultModel.geocodingProgress is pushed into NearbyModel when it changes.
- filtered decadesMap and venueDigests are now VaultModel funcs
> Add and use NearbyModel

- Sources/Site/Music/UI/LocatableMap.swift
- Sources/Site/Music/UI/LocationMap.swift
> LocatableMap is not used with changing Locatables

- Sources/Site/Music/UI/LocationMap.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Utility/MapItem+Geometry.swift
- Sources/Site/Utility/Placemark+Geometry.swift
- Make MKMapItem the common type and remove Locatable.
> Use new Map that uses MapContentBuilder

- Sources/Site/Music/UI/NearbyDistanceThresholdModifier.swift
- Sources/Site/Music/UI/NearbyDistanceThresholdView.swift
- .popover and Slider are not available on tvOS.
- Perhaps try .contextMenu???
> Temporarily Disable Editing Nearby Distance on tvOS

- Sources/Site/Music/UI/NearbyDistanceThresholdModifier.swift
> Disable NearbyDistance toolbar button on tvOS

- Sources/Site/Music/Atlas.swift
- Sources/Site/Music/CNPostalAddress+Geocode.swift
- Sources/Site/Music/Location+Contacts.swift
- Sources/Site/Music/Location+Geocode.swift
- Sources/Site/Music/String+Geocode.swift
- Since it cannot use the Contacts framework.
> tvOS will just geocode hand-generated strings

- .github/dependabot.yml
Swift ecosystem https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#swift
I am unsure if / how this will work but hopefully
https://github.com/bolsinga/site/blob/483e0f8dca65fe79c9fb2e0b9040c118e92c344f/Package.swift#L20
will be upgraded https://github.com/apple/swift-argument-parser/releases
> Add Swift dependencies to dependabot

- Sources/Site/Music/Lookup.swift
> os.Logger is preconcurrency

- Sources/Site/Music/UI/LibraryComparableList.swift
- Sources/Site/Utility/LibrarySectioner.swift
- get some logic out of UI code.
> add LibrarySectioner.sectionMap()

- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArchiveSearchModifier.swift
- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/RankingList.swift
- Sources/Site/Music/UI/VenueList.swift
- Sources/Site/Utility/LibraryComparable.swift
- Add a ViewModiifer for search instead of down in RankingList.
> Filter items via search string at a higher level

- Sources/Site/Music/UI/ArtistDigest+ArtistSort.swift
- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/ArtistSort.swift
- Sources/Site/Music/UI/VenueDigest+VenueSort.swift
- Sources/Site/Music/UI/VenueList.swift
- Sources/Site/Music/UI/VenueSort.swift
- This way ArtistSort and VenueSort are identical.
> rename to .associatedRank

- Sources/Site/Music/RankingSort.swift
- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/SortModifier.swift
- Sources/Site/Music/UI/VenueList.swift
- Sources/Site/Resources/Localizable.xcstrings
- and override it in the closures where appliable.
> Add a default localizedString for RankingSort

- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/Ranking+RankingSort.swift
- Sources/Site/Music/UI/VenueList.swift
> Add and use Ranking+RankingSort

- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/VenueList.swift
- this makes ArtistList and VenueList nearly identical.
> add associatedRankSectionHeader closure

- Sources/Site/Music/Rankable.swift
- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/RankableSortList.swift
- Sources/Site/Music/UI/VenueList.swift
- ArtistList and VenueList now populate RankableSortList behind the scenes.
- Sharing more code!
> Add RankableSortList

- Sources/Site/Music/UI/ArtistList.swift
- Sources/Site/Music/UI/RankableSortList.swift
- Sources/Site/Music/UI/RankingList.swift
- Sources/Site/Music/UI/VenueList.swift
- Sources/Site/Utility/String+AttributedMatching.swift
- Sources/Site/Utility/String+EmphasizedMatching.swift
- Tests/SiteTests/EmphasizedMatchingTests.swift
- This restores #810, #811, #812, and fixes an issue when rendering found that inspired me to back out #815.
- A night's sleep found this solution.
> Render the search matches in bold

- Sources/Site/Music/UI/ArchiveTab.swift
- Sources/Site/Music/UI/ArchiveTabView.swift
- Sources/Site/Music/UI/SiteView.swift
- Sources/Site/Resources/Localizable.xcstrings
This is iOS only at the moment. There is a classic tab to show the old UI.
> Add a TabView that only has a Classic Tab

- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArchiveCategoryShareActivityModifier.swift
.shareCategory() and .archiveCategoryUserActivity() should be used together, so make a ViewModifier that combines them.
> Combine two modifiers into one

- Sources/Site/Music/UI/ArchiveStateView.swift
This reverts commit 082f041aceda332cdb513e6d38d581ccb83c3b3a.
> Revert "disable tab for an updated release (#833)"

- Tests/SiteTests/ArchiveNavigationTests.swift
changing category, checking path
and modify the doubles tests
> Back fill tests regarding category/path

- Sources/Site/Music/UI/ArchiveNavigation.swift
Set them instead of creating new State.
> ArchiveNavigation.State has vars

- Sources/Site/Music/ArchivePath+PathRestorable.swift
- Sources/Site/Music/UI/MusicDestinationModifier.swift
gets logic out of view modifier.
> Add helper methods on Array<ArchivePath>

- Sources/Site/Music/ArchivePath.swift
missed removing this along with #845
> remove jsonData extension on ArchivePath

- Sources/Site/Utility/Date+Weekdays.swift
- Tests/SiteTests/WeekdayTests.swift
broken for a whole year by #447. at least now there are tests!
> fix firstWeekday calculation

- Sources/Site/Music/UI/VenueDetail.swift
CLPlacemark is not Sendable here. follow up to #874
> Still need preconcurrency for Xcode15.4

- Sources/Site/Music/UI/NearbyDistanceThresholdView.swift
follow up to #873 with Xcode 15.4
> annotate NearbyDistanceThresholdView with MainActor

- Sources/Site/Music/UI/VenueDetail.swift
need to @preconcurrency before anything else brings in code!
> ignore format so imports are not moved around

- Sources/Site/Diary/Diary.swift
- Sources/Site/Diary/Entry.swift
This allows this to build with swift 6.0. Similar change made for Music awhile ago.
> Make Diary Sendable

- Sources/Site/Music/UI/ArchiveCategoryShareModifier.swift
just move around the conditional
> Do not have toolbar w/o a url

- Sources/Site/Music/UI/PathRestorableShareModifier.swift
> Also do not have toolbar w/o url

- Sources/Site/Music/Atlas.swift
- Sources/Site/Music/AtlasCache.swift
- Sources/Site/Music/Lookup.swift
- Sources/Site/Music/Music+URL.swift
- Sources/Site/Music/NSUserActivity+ArchiveCategory.swift
- Sources/Site/Music/NSUserActivity+ArchivePath.swift
- Sources/Site/Music/SiteModel.swift
- Sources/Site/Music/UI/ArchiveCategoryShareActivityModifier.swift
- Sources/Site/Music/UI/ArchiveNavigation.swift
- Sources/Site/Music/UI/ArchiveStateView.swift
- Sources/Site/Music/UI/NotificationModifier.swift
- Sources/Site/Music/UI/SiteView.swift
- Sources/Site/Music/Vault+URL.swift
- Sources/Site/Music/VaultModel.swift
- Sources/Site/Utility/Data+JSON.swift
- Sources/Site/Utility/LocationManager.swift
FWIW this is independent of Swift 6.0; the SDKs mark this as Sendable!
> Logger is now Sendable when building with Xcode 16.0

- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
this preview always gets compiler errors so make a funneled initializer, since only the ArchiveCategory value changes.
> add a preview only init

- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArtistsSummary.swift
- Sources/Site/Music/UI/ShowsSummary.swift
- Sources/Site/Music/UI/StatsSummary.swift
- Sources/Site/Music/UI/TodaySummary.swift
- Sources/Site/Music/UI/VenuesSummary.swift
They are currently the detail for the Navigation, but this is what can be used by Tabs in the future.
> Create Summary views for ArchiveCategory.

- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArchiveCategorySplit.swift
This reverts commit 9fe5dfed20d09781e7f798e6ece1d3d38e09567c.
> Revert "Add closure to get [ArchivePath] from a ArchiveCategory (#906)"

- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Sources/Site/Music/UI/CategoryDetailModifier.swift
- this allows it to show when using tabs on iOS.
> Move Nearby for iOS

- Sources/Site/Music/NSUserActivity+ArchivePath.swift
- Sources/Site/Music/UI/ArchiveStateView.swift
- allows another Logger extension to be fileprivate.
> change name of logger about external events.

- Sources/Site/Music/AnnumDigest+NSUserActivity.swift
- Sources/Site/Music/ArtistDigest+NSUserActivity.swift
- Sources/Site/Music/PathRestorable.swift
- Sources/Site/Music/UI/ArtistDetail.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Music/UI/YearDetail.swift
- Sources/Site/Music/VenueDigest+NSUserActivity.swift
- Tests/SiteTests/PathRestorableUserActivityTests.swift
This helps untangle things for a future change. Now that there is a common way to connect things, the ad-hoc parts of the past may be cleaned up.
> pathRestorableUserActivityModifier now takes the "digest"

- Sources/Site/Music/NSUserActivity+ArchivePath.swift
- Sources/Site/Music/UI/ArtistDetail.swift
- Sources/Site/Music/UI/PathRestorableUserActivityModifier.swift
- Sources/Site/Music/UI/ShowDetail.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Music/UI/YearDetail.swift
- Tests/SiteTests/PathRestorableUserActivityTests.swift
> Add PathRestorableUserActivity.url

- Sources/Site/Music/UI/ArchiveSharable.swift
- Sources/Site/Music/UI/ArtistDetail.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Music/UI/YearDetail.swift
> Make digests ArchiveSharable

- Sources/Site/Music/UI/ArchiveNavigationUserActivityModifier.swift
- Sources/Site/Music/UI/ArchiveSharableModifier.swift
- Sources/Site/Music/UI/ArtistDetail.swift
- Sources/Site/Music/UI/ShowDetail.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Music/UI/YearDetail.swift
- Sources/Site/Utility/Linkable.swift
More refactoring toward getting ShareLink into ArchiveNavigationUserActivityModifier
> Add Linkable protocol

- Sources/Site/Music/UI/ArchiveSharableModifier.swift
- Sources/Site/Music/UI/ArchiveSharableToolbar.swift
- Sources/Site/Music/UI/LocationFilterModifier.swift
- Sources/Site/Music/UI/LocationFilterToolbarContent.swift
- Sources/Site/Music/UI/NearbyDistanceThresholdModifier.swift
- Sources/Site/Music/UI/NearbyDistanceThresholdToolbarContent.swift
- Sources/Site/Music/UI/SortModifier.swift
- Sources/Site/Music/UI/SortModifierToolbarContent.swift
- This will set up to allow exploring having one .toolbar in the app, so placement may be more managable.
> Extract ToolbarContent into their own files.

- Sources/Site/Music/UI/LocationFilterModifier.swift
- Sources/Site/Music/UI/NearbyLocationView.swift
The plan is to extract UI from work for the ViewModifiers. This way the UI, the work, and the .toolbar parts can all be separated, in order to try out a single .toolbar for the StateView.
> Extract NearbyLocationView

- Sources/Site/Music/UI/SortModifier.swift
- Sources/Site/Music/UI/SortModifierToolbarContent.swift
> Always using RankingSort

- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Sources/Site/Music/UI/ArchiveStateView.swift
> isCategoryActive no longer used

- Sources/Site/Music/ArchivePath+PathRestorable.swift
- Sources/Site/Music/UI/ArchiveActivity.swift
- Sources/Site/Music/UI/ArchiveNavigation.swift
- Sources/Site/Music/UI/ArchiveNavigationUserActivityModifier.swift
- Tests/SiteTests/ArchiveNavigationTests.swift
This is the current UI @State. It simplifies this so that more may use it. Nice clean up.
> Add ArchiveActivity

- Sources/Site/Music/UI/ArchiveCategoryDetail.swift
- Sources/Site/Music/UI/ArchiveCategorySplit.swift
- Sources/Site/Music/UI/CategoryDetailModifier.swift
This reverts commit 178d50e0bacf943c08e81085c7b6292d0dc3d20a.
> Revert "Move Nearby for iOS (#911)"

- Sources/Site/Music/UI/ArchiveCategoryLinkable.swift
- Sources/Site/Music/UI/ArchiveSharable.swift
- Sources/Site/Music/UI/ArchiveSharableModifier.swift
- Sources/Site/Music/UI/CategoryDetailModifier.swift
> Add ArchiveCategoryLinkable

- Sources/Site/Music/RankingSort.swift
- Sources/Site/Music/UI/SortModifier.swift
no longer necessary after a few refactors.
> Remove Sorting protocol

- Sources/Site/Music/UI/ArtistsSummary.swift
- Sources/Site/Music/UI/LocationFilterModifier.swift
- Sources/Site/Music/UI/NearbyLocationModifier.swift
- Sources/Site/Music/UI/ShowsSummary.swift
- Sources/Site/Music/UI/VenuesSummary.swift
separates the toolbar from the overlay
> Add separate NearbyLocationModifier

- Sources/Site/Music/UI/ArchiveNavigation.swift
- Tests/SiteTests/ArchiveNavigationTests.swift
Have the tests check for this, and make the minor change to the code to make it so. Sets up for a future diff.
> ArchiveCategory.stats has no path

- Sources/Site/Music/UI/ArchiveNavigation.swift
This way each property can be individually observed. it is not possible to observe the return value of a func.
Read in the State to set them. Create a State from the properties to write it out.
> Make various paths observable properties

- Sources/Site/Music/UI/ArchiveNavigation.swift
> remove ArchiveCategory.hasCategoryPath

- Sources/Site/Music/UI/NearbyDistanceThresholdView.swift
- looks better in landscape and macos
> remove nearby view sizing

- .github/workflows/main.yml
- .github/workflows/release.yml
see https://github.com/bolsinga/itunes_json/pull/784
> github builds with warnings as errors

- Sources/Site/Music/UI/ArchiveCategory.swift
- Useful for upcoming UI work.
> Add ArchiveCategory.systemImage

- Sources/Site/Music/UI/ArchiveCategoryStack.swift
- Sources/Site/Music/UI/ArtistsSummary.swift
- Sources/Site/Music/UI/NearbyLocationModifier.swift
- Sources/Site/Music/UI/ShowsSummary.swift
- Sources/Site/Music/UI/VenuesSummary.swift
Keep it out of NearbyLocationView, so its previews interfaces are simpler.
> Use the Environment in NearbyLocationModifier

- Sources/Site/Music/UI/ArchiveCategoryRoot.swift
- Sources/Site/Music/UI/ArchiveCategoryStack.swift
- Sources/Site/Music/UI/ArchiveStateView.swift
- Sources/Site/Music/UI/ArchiveTabView.swift
- Sources/Site/Music/UI/SiteView.swift
- This will allow sheet dismissal to work more easily in a subsequent diff
> Attach .refreshable deeper in the UI

- Sources/Site/Music/UI/TodayList.swift
This reverts commit c8fcf5a41d9b000470aa2ba21799cb6dd2a474a0.
> Revert "Use a Section header for Today title (#1050)"

- Sources/Site/Music/UI/ArchiveCategoryStack.swift
- Otherwise future changes will have duplicate toolbar items!
> Move .toolbar after .navigationDestination

- Sources/Site/Music/UI/ArchiveCrossSearchContainer.swift
- Sources/Site/Music/UI/ArchiveCrossSearchView.swift
- Sources/Site/Music/UI/ArchiveStateView.swift
- Sources/Site/Music/UI/ArchiveTabView.swift
- Sources/Site/Resources/Localizable.xcstrings
- Sources/Site/Utility/LibraryComparable.swift
- Implements search across Artists and Venues.
> Use Tab .search role

- Sources/Site/Music/UI/ArchiveCrossSearchView.swift
> Use different icon for Search Tab results

- Sources/Site/Music/UI/ArchiveCategoryStack.swift
> Also use the category to determine if toolbar is shown.

- Sources/Site/Music/Annum.swift
- Sources/Site/Music/Decade.swift
- Sources/Site/Music/UI/ShowYearList.swift
- Tests/SiteTests/AnnumTests.swift
- Tests/SiteTests/DecadeTests.swift
> Allow ShowYearList to be sorted ascending or descending.

- Sources/Site/Music/UI/ArchiveCategory.swift
> Remove ArchiveCategory.label

- Sources/Site/Music/UI/ArchiveNavigation.swift
- Sources/Site/Music/UI/ArchiveStateView.swift
- Sources/Site/Music/UI/ArchiveTabView.swift
- Sources/Site/Music/UI/ShowsMode.swift
- Tests/SiteTests/ArchiveNavigationTests.swift
- Keeps the UI straight.
- Adds unit tests for this behavior!
- Fixes #1131
> Track ShowsMode in ArchiveNavigation

- Sources/MusicData/ArchiveCategory+FormatStyle.swift
- Sources/MusicData/ArchiveCategory+URL.swift
- Sources/MusicData/Vault.swift
- Sources/Site/Music/UI/ArchiveCategoryToolbarContent.swift
- Sources/Site/Music/UI/ArchiveStateView.swift
- Sources/site_associated_domains/Program.swift
- Tests/MusicDataTests/ArchiveCategoryTests.swift
- update site_associated_domains so that stats/settings/search work as universal links.
> All ArchiveCategory have urls

- Sources/App/Localizable.xcstrings
- Sources/Site/Music/UI/NearbyLocationView.swift
- Sources/Site/Music/VaultModel.swift
- If there are any geocode errors, then the progress would not have finished.
- Tweak the geocoding progress ui to say what the progress view is for! I've seen it in the past and was confused.
> Stop geocode progress once it is complete

- .github/workflows/main.yml
- .github/workflows/release.yml
> github actions only build for arm64

- Sources/Site/Music/UI/ArtistDetail.swift
- Sources/Site/Music/UI/StatsGrouping.swift
- Sources/Site/Music/UI/StatsSummary.swift
- Sources/Site/Music/UI/VenueDetail.swift
- May have been closures when it was hard to calculate; they are all calculated up front now.
- Use better names.
> StatsGrouping properties are now Ranking types

- SiteApp.xcodeproj/project.pbxproj
- Sources/App/Localizable.xcstrings
- Sources/Site/Music/UI/StatsGrouping.swift
- Sources/Site/Music/UI/TitledSheetModifier.swift
It's now a modal instead of a leaf node on the navigation stack.
> Add TitledSheetModifier, used by stats for weekdays and months

- Sources/MusicData/LibraryComparator+Music.swift
- Sources/MusicData/LibrarySectioner+Music.swift
- Sources/MusicData/Lookup.swift
- Sources/MusicData/Vault+URL.swift
- Sources/MusicData/Vault.swift
- Tests/SiteTests/ConcertComparatorTests.swift
- Remove static create async functions
> Use init async

- Sources/MusicData/AnnumDigest.swift
- Sources/MusicData/Vault+AnnumDigest.swift
- Sources/MusicData/Vault.swift
- Sources/Site/Music/UI/ArchivePath+Destination.swift
- Sources/Site/Music/UI/YearDetail.swift
- Sources/Site/Music/Vault+ArchivePath.swift
This consistency is good work towards maybe a faster start up time via saving more information...
> Initialize AnnumDigests up-front like other Digests

- SiteApp.xcodeproj/project.pbxproj
- Sources/Site/Music/UI/ArtistDetail.swift
- Sources/Site/Music/UI/Stats.swift
- Sources/Site/Music/UI/StatsGrouping+Digest.swift
- Sources/Site/Music/UI/StatsGrouping.swift
- Sources/Site/Music/UI/StatsSummary.swift
- Sources/Site/Music/UI/VenueDetail.swift
- Sources/Site/Music/UI/YearDetail.swift
This is because while the Stats will be consistent with future refactors, the title may not be.
> StatsGrouping has the LocalizedStringResource

- SiteApp.xcodeproj/project.pbxproj
- Sources/Site/Music/UI/StatsGrouping+Digest.swift
- Sources/Site/Music/UI/StatsGrouping.swift
- Sources/Site/Music/UI/StatsTitles+Digest.swift
- Sources/Site/Music/UI/StatsTitles.swift
- Encapsulates titles for stats, since two types will be used in a future PR.
- Add StatsTitles.generic for the button names.
> Add StatsTitles
